### PR TITLE
Message list virtualization

### LINKED ISSUE #1971: [bug] Dyad crashes when loading a chat with a lot of messages
## Bug Description (required)
I have a very large app file with multiple chats. Since the recent update I have not be able to load that app. Once I hit "open chat" it starts the process, I see the chat history, and it begins to load the preview. Shortly after it crashes. For context the app is on its 2222 version and a series of complex components.  

## Steps to Reproduce (required)
 click open chat of my existing app. 

## Expected Behavior (required)
 I expected the app to load as it normally would.

## Actual Behavior (required)
The app crashes after a period of loading. 

## Screenshot (Optional)

Image

## System Information
- Dyad Version: 0.30.0
- Platform: win32
- Architecture: x64
- Node Version: v22.14.0
- PNPM Version: 10.14.0
- Node Path: C:\Program Files\nodejs\node.exe
- Pro User ID: ****o1ia
- Telemetry ID: dfa8e45b-ddec-4f37-94a7-a46f645bacb2
- Model: google:gemini-2.5-pro | customId: undefined

## Logs
```



```

### PR DESCRIPTION
**Pull request by azizmejri1**
Closes #1971

---
## Summary by cubic
Virtualized the chat message list with react-virtuoso for smoother scrolling and lower memory use in long chats, with non-virtualized rendering in E2E builds for stable tests. Memoized ChatMessage to reduce unnecessary re-renders.

- **New Features**
  - Switched MessagesList to Virtuoso with itemContent, overscan, smooth follow, and initial focus on the latest message.
  - Moved context limit and Undo/Retry controls into a footer; preserved empty/setup states.

- **Dependencies**
  - Added react-virtuoso ^4.17.0.

<sup>Written for commit f82a976c70bebf40d5c7af7de514e0afde604c64. Summary will update automatically on new commits.</sup>

---

> [!NOTE]
> Virtualizes the chat message list with react-virtuoso, adds a non-virtualized path for E2E via E2E_TEST_BUILD, and refactors footer/actions with memoized ChatMessage.
> 
> - **Frontend (chat)**:
>   - Switch `src/components/chat/MessagesList.tsx` to `react-virtuoso` with `itemContent`, `components.Footer`, overscan, and smooth follow; extract `FooterComponent` for context limit + Undo/Retry controls.
>   - Add E2E test mode using `envVars.E2E_TEST_BUILD` to render non-virtualized list; improve empty/setup handling; memoize `ChatMessage`.
> - **Electron/IPC**:
>   - Include `E2E_TEST_BUILD` in `get-env-vars` so renderer can access test-mode flag.
> - **Dependencies**:
>   - Add `react-virtuoso`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 1c71fe7555a6a32ff29ef1034b889822527484ba. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by wwwillchen** [comment]
@bugbot run

File: src/ipc/handlers/app_handlers.ts [hunk 1]
```diff
@@ -794,6 +794,7 @@ export function registerAppHandlers() {
         envVars[provider.envVarName] = getEnvVar(provider.envVarName);
       }
     }
+    envVars.E2E_TEST_BUILD = process.env.E2E_TEST_BUILD;
```
Comment (wwwillchen) [inline src/ipc/handlers/app_handlers.ts]: Same comment as other PR:

you can detect if you're in e2e test mode in the UI thread, by doing this:

```
settings?.isTestMode
```

**Review by wwwillchen — APPROVED** [review]
LGTM 

free to merge once you've addressed the comment.
