### PR TITLE
Fixing regression and adding plus button to HomeChatInput

### LINKED ISSUE #2127: Unable To Upload Files To Codebase
Session ID: 726a0eea-bf5a-4b7e-b762-7b409d389c36
Pro User ID: ****iLCm

## Issue Description (required)
Going to + > Attach Files > Attach Files To Codebase does nothing. Chat window doesn't show the image after attaching it. 

## Expected Behavior (required)
Show image in chat.

## Actual Behavior (required)
Doesn't do anything.

### PR DESCRIPTION
**Pull request by azizmejri1**
closes #2127 
This PR includes 

- Fixing the regression introduced in the beta release
- Adding the plus button to HomeChatInput

I will create a follow-up PR that makes the e2e test more realistic

---
## Summary by cubic
Adds a plus actions menu to HomeChatInput for attachments and fixes the beta regression that prevented attaching files in home chat.

- **New Features**
  - Added AuxiliaryActionsMenu to HomeChatInput with an “Attach files” submenu; hides context picker and token toggle when not needed.
  - Made menu props optional (showTokenBar/toggle) and added hideContextFilesPicker, improving reuse across inputs.

- **Bug Fixes**
  - Restored file upload by handling menu item onSelect and closing the submenu after selection; inputs reset to allow re-uploading the same file.
  - Updated the e2e test to open the menu, hover “Attach files,” upload via the file input, and close with Escape.

<sup>Written for commit 3db5abc98c9f968cb04eb355a586209e4725be30. Summary will update on new commits.</sup>

---

> [!NOTE]
> Introduces a consolidated plus “AuxiliaryActionsMenu” for file/context actions in both chat inputs and fixes attachment menu interactions.
> 
> - Adds `AuxiliaryActionsMenu` with optional `showTokenBar/toggle`, `showContextFilesPicker`, and `isStreaming`; disables attach submenu while streaming and conditionally shows context picker and token toggle
> - Refactors `FileAttachmentDropdown` to render only menu items + hidden inputs, use `onSelect` to trigger file pickers, clear input values, and close parent via `onMenuClose`
> - Integrates the new menu into `HomeChatInput` and `ChatInput`; keeps `ChatInputControls` and hides context picker where not needed
> - Updates e2e tests to interact with the new menu, including attach-as-context, upload-to-codebase, and drag-and-drop flows; standardizes snapshots and closes menus via Escape
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 6b0d1f24b069a9e9b066f8dba59a8f43af318a08. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by wwwillchen** [comment]
@bugbot run

File: src/components/chat/AuxiliaryActionsMenu.tsx [hunk 1]
```diff
@@ -19,14 +19,18 @@ interface AuxiliaryActionsMenuProps {
...
+  toggleShowTokenBar?: () => void;
+  showContextFilesPicker?: boolean;
+  isStreaming?: boolean;
 }
 
 export function AuxiliaryActionsMenu({
   onFileSelect,
   showTokenBar,
   toggleShowTokenBar,
+  showContextFilesPicker = true,
```
Comment (wwwillchen) [inline src/components/chat/AuxiliaryActionsMenu.tsx]: let's remove this default value *or* flip it so it's (hideContextFilesPicker), true is a surprising default value

File: src/components/chat/AuxiliaryActionsMenu.tsx [hunk 2]
```diff
@@ -47,42 +51,45 @@ export function AuxiliaryActionsMenu({
       </DropdownMenuTrigger>
       <DropdownMenuContent align="end">
         {/* Codebase Context */}
-        <ContextFilesPicker />
+        {showContextFilesPicker && <ContextFilesPicker />}
 
         {/* Attach Files Submenu */}
         <DropdownMenuSub>
-          <DropdownMenuSubTrigger className="py-2 px-3">
+          <DropdownMenuSubTrigger className="py-2 px-3" disabled={isStreaming}>
```
Comment (wwwillchen) [inline src/components/chat/AuxiliaryActionsMenu.tsx]: i don't think we should disable this while it's streaming (not sure why we did this previously, tbh)

File: src/components/chat/AuxiliaryActionsMenu.tsx [hunk 3]
```diff
@@ -47,42 +51,45 @@ export function AuxiliaryActionsMenu({
...
-              showTokenBar
-                ? "text-primary group-hover:text-accent-foreground"
-                : ""
-            }
-          />
-          <span className="flex-1">
-            {showTokenBar ? "Hide" : "Show"} token usage
-          </span>
-        </DropdownMenuItem>
+        {toggleShowTokenBar !== undefined && (
```
Comment (wwwillchen) [inline src/components/chat/AuxiliaryActionsMenu.tsx]: simplify to `toggleShowTokenBar && ` ? (more idiomatic JS)

File: src/components/chat/FileAttachmentDropdown.tsx [hunk 4]
```diff
@@ -1,34 +1,24 @@
...
-  renderAsMenuItems?: boolean;
+  onMenuClose?: () => void;
 }
 
 export function FileAttachmentDropdown({
   onFileSelect,
-  disabled,
-  className,
-  renderAsMenuItems = false,
+  onMenuClose,
```
Comment (wwwillchen) [inline src/components/chat/FileAttachmentDropdown.tsx]: should name this closeMenu because it's triggering menu close

File: src/components/chat/FileAttachmentDropdown.tsx [hunk 5]
```diff
@@ -58,7 +50,10 @@ export function FileAttachmentDropdown({
         <Tooltip>
           <TooltipTrigger asChild>
             <DropdownMenuItem
-              onClick={handleChatContextClick}
+              onSelect={(e) => {
+                e.preventDefault();
```
Comment (wwwillchen) [inline src/components/chat/FileAttachmentDropdown.tsx:56]: Add a comment here so we remember why we did this, e.g. 

// Prevent default so menu doesn't close in order to keep the hidden inputs in this in the DOM
// Manually close menu after file selection

File: src/components/chat/FileAttachmentDropdown.tsx [hunk 6]
```diff
@@ -75,7 +70,10 @@ export function FileAttachmentDropdown({
         <Tooltip>
           <TooltipTrigger asChild>
             <DropdownMenuItem
-              onClick={handleUploadToCodebaseClick}
+              onSelect={(e) => {
```
Comment (wwwillchen) [inline src/components/chat/FileAttachmentDropdown.tsx:75]: ditto above

**Review by wwwillchen — APPROVED** [review]
thanks for the quick fix! left some minor code health comments, otherwise LGTM.
