### PR TITLE
Enhance Azure configuration handling and UI updates

### LINKED ISSUE #1275: [bug] AZURE AI - Not picking up ENV AZURE_RESOURCE_NAME
## System Information
- Dyad Version: 0.20.0
- Platform: win32
- Architecture: x64
- Node Version: v22.14.0
- PNPM Version: 10.15.1
- Node Path: C:\Program Files\nodejs\node.exe
- Telemetry ID: c4699296-266f-4957-aa3b-e168dfe60dc0
- Model: auto:auto | customId: undefined

## Logs
```
[2025-09-12 19:48:23.278] [error] (chat_stream_handlers) Error streaming text: {
  error: 'AI_RetryError: Failed after 3 attempts. Last error: Resource has been exhausted (e.g. check quota).\n' +
    '    at IEt (C:\\Users\\nathan.tran\\AppData\\Local\\dyad\\app-0.20.0\\resources\\app.asar\\.vite\\build\\main.js:250:38472)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async ee (C:\\Users\\nathan.tran\\AppData\\Local\\dyad\\app-0.20.0\\resources\\app.asar\\.vite\\build\\main.js:254:26995)\n' +
    '    at async fn (C:\\Users\\nathan.tran\\AppData\\Local\\dyad\\app-0.20.0\\resources\\app.asar\\.vite\\build\\main.js:254:31900)\n' +
    '    at async C:\\Users\\nathan.tran\\AppData\\Local\\dyad\\app-0.20.0\\resources\\app.asar\\.vite\\build\\main.js:250:36423'
}
[2025-09-12 19:48:25.310] [error] (tsc) TSC worker exited with code 1 for app C:\Users\nathan.tran\dyad-apps\TEMO
[2025-09-12 19:48:40.035] [error] (tsc) TSC worker exited with code 1 for app C:\Users\nathan.tran\dyad-apps\TEMO
[2025-09-12 19:48:46.288] [error] (chat_stream_handlers) Error streaming text: {
  error: 'AI_RetryError: Failed after 3 attempts. Last error: Resource has been exhausted (e.g. check quota).\n' +
    '    at IEt (C:\\Users\\nathan.tran\\AppData\\Local\\dyad\\app-0.20.0\\resources\\app.asar\\.vite\\build\\main.js:250:38472)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async ee (C:\\Users\\nathan.tran\\AppData\\Local\\dyad\\app-0.20.0\\resources\\app.asar\\.vite\\build\\main.js:254:26995)\n' +
    '    at async fn (C:\\Users\\nathan.tran\\AppData\\Local\\dyad\\app-0.20.0\\resources\\app.asar\\.vite\\build\\main.js:254:31900)\n' +
    '    at async C:\\Users\\nathan.tran\\AppData\\Local\\dyad\\app-0.20.0\\resources\\app.asar\\.vite\\build\\main.js:250:36423'
}
[2025-09-12 19:48:50.067] [error] (tsc) TSC worker exited with code 1 for app C:\Users\nathan.tran\dyad-apps\TEMO

```

### PR DESCRIPTION
**Pull request by rakibulrocky14**
# Changes 

- Update Azure configuration components to manage API key and resource name settings.
- Improve visibility of conThis pull request introduces a redesigned Azure provider settings UI and refactors the logic for configuring Azure OpenAI credentials, both in the frontend and supporting hooks. The main changes focus on making the Azure configuration experience clearer and more robust by supporting both environment variable and saved settings, improving status indicators, and updating the logic for determining provider readiness.

**Azure Provider UI and Logic Improvements**

* Added a new `AzureConfiguration` component that provides a dedicated form for entering and saving Azure resource name and API key, with clear status indicators and error handling. The UI now explains precedence between saved settings and environment variables, and guides users through configuration. (`src/components/settings/AzureConfiguration.tsx`)
* Updated the main provider settings page and API key configuration logic to pass Azure-specific settings and update functions to the new component, ensuring seamless integration and correct state management. (`src/components/settings/ApiKeyConfiguration.tsx`, `src/components/settings/ProviderSettingsPage.tsx`) [[1]](diffhunk://#diff-2104fb487cda3768cc5777889100e882f51e7fb3e13abe3cc89cf8ed1444300aR35) [[2]](diffhunk://#diff-2104fb487cda3768cc5777889100e882f51e7fb3e13abe3cc89cf8ed1444300aR51-R61) [[3]](diffhunk://#diff-9140e707ebb56ffed3272b4661ea1e6d8388ee604a8535c58e8a1564d280057cR297)
* Refactored the logic for determining whether Azure is configured to check both saved settings and environment variables, ensuring accurate status display and enabling fallback to environment variables if no settings are saved. (`src/components/settings/ProviderSettingsPage.tsx`, `src/hooks/useLanguageModelProviders.ts`) [[1]](diffhunk://#diff-9140e707ebb56ffed3272b4661ea1e6d8388ee604a8535c58e8a1564d280057cL72-R99) [[2]](diffhunk://#diff-9ac9e279a0cda34a0bc519348d5474b2e355b0828a678495be3af1e8984b5be5R35-R48)
* Updated the Azure provider E2E test to verify the new UI elements, status indicators, and guidance, ensuring the test matches the new configuration flow and messaging. (`e2e-tests/azure_provider_settings.spec.ts`)

**Supporting Type and Import Updates**

* Added and updated type imports for `AzureProviderSetting` and `VertexProviderSetting` where needed to support the new logic and UI. (`src/components/settings/ProviderSettingsPage.tsx`, `src/hooks/useLanguageModelProviders.ts`, `src/ipc/utils/get_model_client.ts`) [[1]](diffhunk://#diff-9140e707ebb56ffed3272b4661ea1e6d8388ee604a8535c58e8a1564d280057cL14-R14) [[2]](diffhunk://#diff-9ac9e279a0cda34a0bc519348d5474b2e355b0828a678495be3af1e8984b5be5L5-R5) [[3]](diffhunk://#diff-3cd526c6c10413c1387bfef450e48b880ba6f54865e96046044586ff4192bcceR15)
* Changed Azure model client import to use `createAzure` for consistency and future extensibility. (`src/ipc/utils/get_model_client.ts`)
[Copilot is generating a summary...]figuration status and error handling in the UI.
- Refactor environment variable checks to prioritize saved settings.
- Add support for Azure provider settings in the schema.
- Modify tests to reflect changes in Azure configuration requirements.

# Changes in short

- **Azure settings panel**
  - Replaced with a full form that:
    - Persists API key and resource name  
    - Surfaces save state  
    - Keeps the environment-variable helper  
  - *(src/components/settings/AzureConfiguration.tsx:23-214)*

- **Settings stack workflow**
  - Threaded the new Azure workflow:
    - Config shim now passes `updateSettings`  
    - Provider status checks prefer saved Azure values before env vars  
  - *(src/components/settings/ApiKeyConfiguration.tsx:40-55, src/components/settings/ProviderSettingsPage.tsx:60-105)*

- **Provider detection**
  - Azure treated like other saved credentials by:
    - Looking for both stored fields, or  
    - The pair of env vars  
  - *(src/hooks/useLanguageModelProviders.ts:5-57)*

- **Back-end model creation**
  - Reads saved Azure credentials (falling back to env vars)  
  - Builds the client via `createAzure`  
  - *(src/ipc/utils/get_model_client.ts:316-369)*

- **Provider schema support**
  - Extended so Azure can store its resource name alongside the secret  
  - *(src/lib/schemas.ts:82-109)*  

- **E2E tests**
  - Updated Azure Playwright spec to cover the new UI  
  - *(e2e-tests/azure_provider_settings.spec.ts:4-50)*

Issues resolved: #1275

### CODE REVIEW

**Comment by rakibulrocky14** [comment]
I hope it will be easy for beginners now

File: src/components/settings/AzureConfiguration.tsx [hunk 1]
```diff
@@ -1,119 +1,266 @@
...
+  const [apiKey, setApiKey] = useState(existingApiKey);
+  const [resourceName, setResourceName] = useState(existingResourceName);
+  const [saving, setSaving] = useState(false);
+  const [saved, setSaved] = useState(false);
+  const [error, setError] = useState<string | null>(null);
+
+  useEffect(() => {
+    setApiKey(existingApiKey);
+    setResourceName(existingResourceName);
+  }, [existingApiKey, existingResourceName]);
```
[the remark this answers is not in the document]
Comment (rakibulrocky14) [reply src/components/settings/AzureConfiguration.tsx:43]: it still does make sense

**Comment by wwwillchen** [comment]
@rakibulrocky14 thanks for the PR! I kicked off GitHub Actions and noticed the presubmit formatting check is failing. Could you follow: https://github.com/dyad-sh/dyad/blob/main/CONTRIBUTING.md#setup? This will run the formatter for each commit. You can also format explicitly by running: `npm run prettier`

**Comment by rakibulrocky14** [comment]
@wwwillchen , I ran `npm run prettier` and updated. Thanks

**Comment by rakibulrocky14** [comment]
@wwwillchen , I fixed the issue of test file

**Comment by rakibulrocky14** [comment]
@wwwillchen I addressed the issue and hopeful that this time it will not fail anymore

**Comment by rakibulrocky14** [comment]
@wwwillchen I got the issue I am fixing

**Comment by rakibulrocky14** [comment]
# Problem: Flaky E2E Snapshot Tests

## Summary
End-to-end tests are intermittently failing because snapshots are taken while the chat message list is still changing.

## Failing Test
- e2e-tests/chat_mode.spec.ts — "dyadwrite edit and save - basic flow"
  - Assertion fails when matching ARIA snapshot for `[data-testid="messages-list"]`.

## Root Cause
- Tests call snapshot immediately after clicking "Save".
- The app may still be streaming or finalizing assistant messages or re-rendering the messages list when the snapshot is taken.
- Existing helpers:
  - `saveFile()` returns as soon as the Save button is clicked (no guarantee of post-save completion).
  - `waitForChatCompletion()` checks for a "Retry" button, which is not a reliable signal that the new message stream is finished.
  - `snapshotMessages()` has no stability guard; it may capture the DOM mid-mutation.

## Contributing Flake
- Capacitor-related tests sometimes assert `no-app-upgrades-needed` before a background check finishes.
- Repeated "Error reading AI_RULES.md" logs are benign (fixtures intentionally lack AI_RULES.md) and not the cause.

## Suggested Fix
1. Add a stability wait (e.g., `waitForStableMessages()`) that polls a lightweight signature of the messages list until it is stable.
2. Call that stability wait inside `snapshotMessages()` before taking the ARIA snapshot.
3. Make `saveFile()` wait for chat completion and for the messages list to stabilize before returning.
4. Harden the app-upgrade visibility assertion with a retry/await for the background check to finish.
5. (Optional) Lower the log level for missing AI_RULES.md to avoid noise.

## Impact
- Fixes flaky snapshot failures that are due to timing, not functional regressions.
- Changes are confined to test helpers; production code remains unchanged.

## Minimal Next Step
- Update `e2e-tests/helpers/test_helper.ts` to include `waitForStableMessages()` and call it in `saveFile()` and `snapshotMessages()`, then re-run CI.

**Comment by rakibulrocky14** [comment]
@wwwillchen if you want I can open a PR for it

**Comment by rakibulrocky14** [comment]
The root cause is snapshotting the messages list before it stabilizes after a save/chat completion (a race condition). The capacitor test flakiness is a separate async visibility race. AI_RULES.md logs are unrelated. Stabilizing the message list and waiting after save should resolve the failures.

**Comment by rakibulrocky14** [comment]
@wwwillchen if you want I can open a PR for it

**Comment by rakibulrocky14** [comment]
@wwwillchen do I need to fix this?

File: src/lib/schemas.ts [hunk 2]
```diff
@@ -82,6 +82,7 @@ export type LargeLanguageModel = z.infer<typeof LargeLanguageModelSchema>;
  */
 export const RegularProviderSettingSchema = z.object({
   apiKey: SecretSchema.optional(),
+  resourceName: z.string().optional(),
```
Comment (wwwillchen) [inline src/lib/schemas.ts:103]: let's remove this

**Review by wwwillchen — CHANGES_REQUESTED** [review]
overall looks good! just needs one small change and then I think we can merge.

agree, i think the test failures look like unrelated flakiness

File: src/lib/schemas.ts (hunk 2 above)
Comment (rakibulrocky14) [reply src/lib/schemas.ts:103]: Ok

**Comment by rakibulrocky14** [comment]
@wwwillchen

**Comment by wwwillchen** [comment]
@rakibulrocky14 the resource name does not seem to be persisted properly - could you double check?

**Comment by rakibulrocky14** [comment]
@wwwillchen can you check now? 
I hope it is fine now

**Comment by wwwillchen** [comment]
@rakibulrocky14 works now, thanks!

**Review by wwwillchen — APPROVED** [review]
